import type { LucideIcon } from "lucide-react";
import {
  Award,
  BriefcaseBusiness,
  CircleUserRound,
  Code2,
  ExternalLink,
  FileText,
  FolderKanban,
  GitBranch,
  GraduationCap,
  Pencil,
  Plus,
  House,
  Mail,
  Rocket,
  Route,
  Settings2,
  Sparkles,
  Trophy,
  Trash2,
  X,
  Wrench,
} from "lucide-react";

export const moduleIcons = {
  home: House,
  about: CircleUserRound,
  projects: FolderKanban,
  skills: Wrench,
  journey: Route,
  achievements: Trophy,
  eportfolio: GraduationCap,
  contact: Mail,
} satisfies Record<string, LucideIcon>;

export {
  Award,
  BriefcaseBusiness,
  CircleUserRound,
  Code2,
  ExternalLink,
  FileText,
  FolderKanban,
  GraduationCap,
  GitBranch as Github,
  BriefcaseBusiness as Linkedin,
  Pencil,
  Plus,
  Mail,
  Rocket,
  Route,
  Settings2,
  Sparkles,
  Trophy,
  Trash2,
  X,
  Wrench,
};
